version: '3.9'

services:
  instance1:
    build:
      context: .
      dockerfile: Dockerfile-iptables
      args:
        CONFIG_TCP_SERVER_PORT: 9876
        CONFIG_PLUGIN_LIST: "simple-plugin.jar"
    ports:
      - "9876:9876/udp"  # Map UDP port 9876 from the host to the container
    environment:
      CONFIG_TCP_SERVER_PORT: 9876
      CONFIG_PLUGIN_LIST: "simple-plugin.jar"
    networks:
      - custom-network
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW

networks:
  custom-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: custom_bridge  # Name the bridge network
